(ns shiftlefter.agent-doc.agent-md-gen
  "Generator for the repo-root `docs/AGENT.md` agent guide (sl-b06).

   `docs/AGENT.md` is a DERIVED artifact: a single fat file, single-sourced from
   the packaged `sl agent-doc` topics so it cannot drift from them. It ships
   nowhere (not the jar, not the release zip) — its only audience is someone
   reading the repo on GitHub or after a clone. Release/jar agents read the same
   doctrine through `sl agent-doc <topic>`; this file is the inlined view.

   Same single-source discipline as `builtins-gen`: `render` is a pure function
   of its `[{:topic :content}]` input so it is determinism- and drift-testable;
   `generate` loads the live packaged topic resources. Regenerate with
   `clojure -T:build gen-agent-md` (after `gen-builtins`, since the `builtins`
   topic is itself generated)."
  (:require [clojure.string :as str]
            [shiftlefter.agent-doc :as agent-doc]))

(def ^:private banner
  "The single H1 + a do-not-edit warning. Topic headings are demoted under this."
  (str "# AGENT.md — ShiftLefter agent guide\n"
       "\n"
       "> GENERATED — do not edit this file. It is single-sourced from the\n"
       "> packaged `sl agent-doc` topics in `resources/shiftlefter/agent_docs/`.\n"
       "> Edit a topic there and run `clojure -T:build gen-agent-md` (the\n"
       "> `builtins` topic regenerates via `gen-builtins`). With the jar, read\n"
       "> these same topics live with `sl agent-doc <topic>`.\n"))

(defn- demote-headings
  "Push every Markdown ATX heading down one level so topic titles sit under the
   single AGENT.md H1 (`# X` -> `## X`)."
  [content]
  (->> (str/split-lines content)
       (map (fn [line]
              (if (re-find #"^#+ " line)
                (str "#" line)
                line)))
       (str/join "\n")))

(defn- strip-read-next
  "Drop a trailing `Read next:` inter-topic nav block — it points at sibling
   `sl agent-doc` topics that are already inline here."
  [content]
  (let [lines (str/split-lines content)
        idx (->> lines
                 (keep-indexed (fn [i line]
                                 (when (re-find #"(?i)^read next:" line) i)))
                 first)]
    (if idx
      (-> (subvec (vec lines) 0 idx)
          (->> (str/join "\n"))
          str/trimr)
      content)))

(defn- render-topic
  [{:keys [content]}]
  (-> content strip-read-next demote-headings str/trim))

(defn render
  "Pure render of the derived AGENT.md from ordered `[{:topic :content}]` maps."
  [topics]
  (str banner
       "\n"
       (str/join "\n\n---\n\n" (map render-topic topics))
       "\n"))

(defn generate
  "Load the live packaged topic resources in registry order and render."
  []
  (render
   (for [topic (agent-doc/topic-names)
         :let [{:keys [status content]} (agent-doc/load-topic topic)]]
     (if (= :ok status)
       {:topic topic :content content}
       (throw (ex-info "agent-doc topic resource missing during AGENT.md generation"
                       {:topic topic :status status}))))))

(defn write-doc!
  "Exec entry point: write the generated guide to `:out`.

   Invoked from the build via `clojure -X` so generation runs on the project
   classpath (the `-T:build` tool classpath does not see the framework)."
  [{:keys [out]}]
  (spit out (generate))
  (println (str "Wrote " out)))
