(ns shiftlefter.corpus.generator
  "Seeded corpus generator for runner-mechanics acceptance (sl-vs9m).

   (profile, seed) materializes .feature files + manifest.edn under
   target/corpus/<profile>-<seed>/ at test time. Corpus files are never
   committed: a committed corpus drifts from its generator; a generated one
   can't. Same seed + same generator-version = byte-identical output
   (test-enforced). Seed stability holds WITHIN a generator version only
   (seeds-per-version doctrine, D1) -- the verifier only ever compares a run
   against the manifest born in the same generation act.

   The manifest is the machine contract (D2): per-scenario name / feature /
   tags / expected-status / expected-fail-step / duration-floor-ms /
   serial-group. Scenario names encode outcomes for HUMANS ('S-012 fails at
   step 2'); nothing parses names.

   Profiles are DATA (D5) and step emission is table-driven, so future
   slices (e.g. the 0.6 macro era) are data changes, not code branches."
  (:require [babashka.fs :as fs]
            [clojure.spec.alpha :as s]
            [clojure.string :as str]))

(def generator-version
  "Bumped whenever generated bytes for a given (profile, seed) change."
  [1 1])

;; -----------------------------------------------------------------------------
;; Profiles (data, not code branches)
;; -----------------------------------------------------------------------------

(def profiles
  "Preset parameter maps. :default covers the tag matrix at ~8 features /
   ~40 scenarios; :parallel-stress is the same generator with bigger N and
   more serial groups for sl-q9wp wall-clock work (crank :sleep-range-ms
   there when q9wp needs longer scenarios -- a data change)."
  {:default
   {:allow-pending? true
    :sleep-range-ms [10 60]
    :filler-scenarios 12
    :filler-statuses [:passed :passed :passed :passed :failed :error :pending]
    :serial-groups 2
    :serial-scenarios-per-group 3
    :control-scenarios 3}

   :parallel-stress
   {:allow-pending? true
    :sleep-range-ms [10 30]
    :filler-scenarios 60
    :filler-statuses [:passed :passed :passed :passed :failed :error :pending]
    :serial-groups 4
    :serial-scenarios-per-group 4
    :control-scenarios 8}})

;; -----------------------------------------------------------------------------
;; Manifest spec -- the machine contract sl-i608/sl-q9wp acceptance reads
;; -----------------------------------------------------------------------------

(s/def :corpus.scenario/name string?)
(s/def :corpus.scenario/feature-file string?)
(s/def :corpus.scenario/feature-name string?)
(s/def :corpus.scenario/tags (s/coll-of string? :kind vector?))
(s/def :corpus.scenario/expected-status #{:passed :failed :error :pending})
(s/def :corpus.scenario/expected-fail-step (s/nilable string?))
(s/def :corpus.scenario/duration-floor-ms nat-int?)
(s/def :corpus.scenario/serial-group (s/nilable string?))
(s/def :corpus/scenario
  (s/keys :req-un [:corpus.scenario/name
                   :corpus.scenario/feature-file
                   :corpus.scenario/feature-name
                   :corpus.scenario/tags
                   :corpus.scenario/expected-status
                   :corpus.scenario/expected-fail-step
                   :corpus.scenario/duration-floor-ms
                   :corpus.scenario/serial-group]))
(s/def :corpus.manifest/generator-version (s/coll-of nat-int? :kind vector?))
(s/def :corpus.manifest/seed int?)
(s/def :corpus.manifest/profile keyword?)
(s/def :corpus.manifest/config map?)
(s/def :corpus.manifest/scenarios (s/coll-of :corpus/scenario :kind vector?))
(s/def :corpus.manifest/scratch-files (s/map-of string? string?))
(s/def :corpus.manifest/broken map?)
(s/def :corpus/manifest
  (s/keys :req-un [:corpus.manifest/generator-version
                   :corpus.manifest/seed
                   :corpus.manifest/profile
                   :corpus.manifest/config
                   :corpus.manifest/scenarios
                   :corpus.manifest/scratch-files
                   :corpus.manifest/broken]))

;; -----------------------------------------------------------------------------
;; Seeded randomness (the fuzz.clj idiom -- one java.util.Random threaded
;; through in strict left-to-right order; laziness would scramble draws)
;; -----------------------------------------------------------------------------

(defn- rand-int-seeded
  "Random int in [lo, hi] inclusive."
  [^java.util.Random rng lo hi]
  (+ lo (.nextInt rng (inc (- hi lo)))))

(defn- rand-nth-seeded [^java.util.Random rng coll]
  (nth coll (.nextInt rng (count coll))))

;; -----------------------------------------------------------------------------
;; Step emission table (D5): status/kind -> step text
;; -----------------------------------------------------------------------------

(def ^:private final-step-text
  {:failed  "corpus fails deliberately"
   :error   "corpus errors deliberately"
   :pending "corpus is pending"})

(defn- sleep-step [ms] {:keyword "When" :text (str "corpus sleeps " ms " ms")})
(defn- no-op-step [kw] {:keyword kw :text "corpus no-op"})

(defn- marker-step [which scenario-name group scratch-path]
  {:keyword "When"
   :text (str "corpus marks " which " of \"" scenario-name
              "\" in group \"" group "\" at \"" scratch-path "\"")})

;; -----------------------------------------------------------------------------
;; Scenario spec construction
;; -----------------------------------------------------------------------------

(defn- lead-steps
  "1-3 no-op/sleep steps. Returns [steps floor-ms]."
  [rng {:keys [sleep-range-ms]}]
  (let [[lo hi] sleep-range-ms
        n (rand-int-seeded rng 1 3)
        steps (mapv (fn [i]
                      (let [kw (if (zero? i) "Given" "When")]
                        (if (zero? (rand-int-seeded rng 0 1))
                          (no-op-step kw)
                          (assoc (sleep-step (rand-int-seeded rng lo hi))
                                 :keyword kw))))
                    (range n))
        floor (reduce + 0 (keep #(when-let [[_ ms] (re-find #"sleeps (\d+) ms" (:text %))]
                                   (parse-long ms))
                                steps))]
    [steps floor]))

(defn- scenario-name [n status step-count]
  (let [nn (format "S-%03d" n)]
    (case status
      :passed  (str nn " passes")
      :failed  (str nn " fails at step " step-count)
      :error   (str nn " errors at step " step-count)
      :pending (str nn " is pending at step " step-count))))

(defn- plain-scenario
  "A pass/fail/error/pending scenario spec built from the emission table."
  [rng profile n status tags]
  (let [[leads floor] (lead-steps rng profile)
        final (when (not= :passed status)
                {:keyword "Then" :text (final-step-text status)})
        steps (cond-> leads final (conj final))
        name (scenario-name n status (count steps))]
    {:name name
     :tags tags
     :steps steps
     :expected-status status
     :expected-fail-step (when (#{:failed :error} status) (:text final))
     :pending-step (when (= :pending status) (:text final))
     :duration-floor-ms floor
     :serial-group nil}))

(defn- marker-scenario
  "A file-IO scenario writing begin/end markers around a sleep. `group` is a
   serial group name or \"control\" (the ungrouped, interleave-allowed set)."
  [rng profile n group serial? scratch-path]
  (let [[lo hi] (:sleep-range-ms profile)
        name (format "S-%03d %s passes" n (if serial? (str "serial " group) "control"))
        ms (rand-int-seeded rng lo hi)]
    {:name name
     :tags (if serial? ["@serial"] [])
     :steps [(marker-step "begin" name group scratch-path)
             (sleep-step ms)
             (marker-step "end" name group scratch-path)]
     :expected-status :passed
     :expected-fail-step nil
     :pending-step nil
     :duration-floor-ms ms
     :serial-group (when serial? group)}))

;; -----------------------------------------------------------------------------
;; The deliberate coverage core (D5): tag matrix + statuses + Background
;; -----------------------------------------------------------------------------

(defn- outline-spec
  "One Scenario Outline with two Examples blocks -- the second carries a
   block-level tag, so its pickles inherit it (the row-level-tags corner
   sl-i608 will get wrong if untested)."
  [rng profile]
  (let [[lo hi] (:sleep-range-ms profile)
        ms (fn [] (rand-int-seeded rng lo hi))]
    {:outline? true
     :title "O-001 case <case> passes"
     :tags ["@corpus-outline"]
     :steps [(no-op-step "Given")
             {:keyword "When" :text "corpus sleeps <ms> ms"}]
     :examples [{:tags []
                 :rows [{:case "alpha" :ms (ms)} {:case "beta" :ms (ms)}]}
                {:tags ["@corpus-row"]
                 :rows [{:case "gamma" :ms (ms)}]}]}))

(defn- core-features
  "The fixed coverage slice. Returns [features next-n] where each feature is
   {:file :name :tags :background :scenarios}. `next-scenario` is a fn
   drawing the next scenario number."
  [rng profile next-n]
  [{:file "01_feature_tags.feature"
    :name "Corpus feature tags"
    :tags ["@corpus-suite"]
    :scenarios [(plain-scenario rng profile (next-n) :passed [])
                (plain-scenario rng profile (next-n) :failed [])
                (plain-scenario rng profile (next-n) :pending [])]}
   {:file "02_scenario_tags.feature"
    :name "Corpus scenario tags"
    :tags []
    :scenarios [(plain-scenario rng profile (next-n) :passed ["@corpus-a"])
                (plain-scenario rng profile (next-n) :error ["@corpus-a" "@corpus-b"])
                (plain-scenario rng profile (next-n) :passed [])]}
   {:file "03_both_tags.feature"
    :name "Corpus both tags"
    :tags ["@corpus-suite"]
    :scenarios [(plain-scenario rng profile (next-n) :failed ["@corpus-b"])
                (plain-scenario rng profile (next-n) :passed ["@corpus-a"])]}
   {:file "04_outline.feature"
    :name "Corpus outline"
    :tags []
    :scenarios [(outline-spec rng profile)]}
   {:file "05_background.feature"
    :name "Corpus background"
    :tags []
    :background [(no-op-step "Given")]
    :scenarios [(plain-scenario rng profile (next-n) :passed [])
                (plain-scenario rng profile (next-n) :error [])]}
   {:file "06_untagged.feature"
    :name "Corpus untagged"
    :tags []
    :scenarios [(plain-scenario rng profile (next-n) :passed [])
                (plain-scenario rng profile (next-n) :pending [])]}
   ;; Rule tags are in the pickle inheritance chain (sl-i608 addendum 2a):
   ;; dedupe(feature + rule + scenario + examples-block). The top-level
   ;; scenario proves a rule-tag filter selects a strict subset of the file.
   {:file "09_rule_tags.feature"
    :name "Corpus rule tags"
    :tags []
    :scenarios [(plain-scenario rng profile (next-n) :passed [])]
    :rules [{:name "Tagged rule"
             :tags ["@corpus-rule"]
             :scenarios [(plain-scenario rng profile (next-n) :passed [])
                         (plain-scenario rng profile (next-n) :failed [])]}]}])

(defn- serial-feature [rng profile next-n scratch-path-for]
  (let [groups (mapv #(str "g" (inc %)) (range (:serial-groups profile)))]
    {:file "07_serial.feature"
     :name "Corpus serial groups"
     :tags []
     :scenarios (vec (for [g groups
                           _ (range (:serial-scenarios-per-group profile))]
                       (marker-scenario rng profile (next-n) g true
                                        (scratch-path-for g))))}))

(defn- control-feature [rng profile next-n scratch-path-for]
  {:file "08_control.feature"
   :name "Corpus control"
   :tags []
   :scenarios (mapv (fn [_]
                      (marker-scenario rng profile (next-n) "control" false
                                       (scratch-path-for "control")))
                    (range (:control-scenarios profile)))})

(defn- add-filler
  "Distribute seeded filler scenarios across the eligible core features."
  [rng profile next-n features]
  (let [eligible [0 1 2 4 5]  ;; 01 02 03 05 06 -- not the outline feature
        placements (mapv (fn [_]
                           [(rand-nth-seeded rng eligible)
                            (plain-scenario rng profile (next-n)
                                            (rand-nth-seeded rng (:filler-statuses profile))
                                            [])])
                         (range (:filler-scenarios profile)))]
    (reduce (fn [fs [idx sc]] (update-in fs [idx :scenarios] conj sc))
            features
            placements)))

;; -----------------------------------------------------------------------------
;; Rendering (specs -> Gherkin text)
;; -----------------------------------------------------------------------------

(defn- render-tags [indent tags]
  (when (seq tags) (str indent (str/join " " tags) "\n")))

(defn- render-steps [steps]
  (str/join "" (map #(str "    " (:keyword %) " " (:text %) "\n") steps)))

(defn- render-examples [{:keys [tags rows]}]
  (let [cols (vec (keys (first rows)))]
    (str (render-tags "    " tags)
         "    Examples:\n"
         "      | " (str/join " | " (map name cols)) " |\n"
         (str/join "" (map (fn [row]
                             (str "      | " (str/join " | " (map #(str (get row %)) cols)) " |\n"))
                           rows)))))

(defn- render-scenario [sc]
  (if (:outline? sc)
    (str (render-tags "  " (:tags sc))
         "  Scenario Outline: " (:title sc) "\n"
         (render-steps (:steps sc))
         "\n"
         (str/join "\n" (map render-examples (:examples sc))))
    (str (render-tags "  " (:tags sc))
         "  Scenario: " (:name sc) "\n"
         (render-steps (:steps sc)))))

(defn- render-rule [{:keys [name tags scenarios]}]
  (str (render-tags "  " tags)
       "  Rule: " name "\n\n"
       (str/join "\n" (map render-scenario scenarios))))

(defn- render-feature [{:keys [name tags background scenarios rules]}]
  (str (render-tags "" tags)
       "Feature: " name "\n"
       (when background
         (str "\n  Background:\n" (render-steps background)))
       "\n"
       (str/join "\n" (map render-scenario scenarios))
       (when (seq rules)
         (str "\n" (str/join "\n" (map render-rule rules))))))

(def ^:private broken-feature-text
  "The @broken quarantine (D7): an undefined step, generated but EXCLUDED
   from the default run (today it would exit 2 and break the green suite).
   It is sl-i608's sharpest acceptance case: include this file with @broken
   tag-excluded and the suite passes (planning-time filtering); without the
   filter, planning fails."
  (str "@broken\n"
       "Feature: Corpus broken quarantine\n"
       "\n"
       "  Scenario: B-001 has an undefined step\n"
       "    Given corpus step that no stepdef defines\n"))

;; -----------------------------------------------------------------------------
;; Manifest construction (same specs that rendered the features -- one source)
;; -----------------------------------------------------------------------------

(defn- inherited-tags
  "The manifest's independent tag-inheritance oracle: the same
   dedupe(feature + rule + scenario + examples-block) chain the pickler
   flattens into :pickle/tags."
  [feature-tags rule-tags sc-tags example-tags]
  (vec (distinct (concat feature-tags rule-tags sc-tags example-tags))))

(defn- scenario-entries
  "Per-PICKLE manifest entries for one scenario spec (outline rows expand).
   `rule-tags` is [] for scenarios not under a Rule."
  [file feature-name feature-tags rule-tags sc]
  (if (:outline? sc)
    (for [ex (:examples sc)
          row (:rows ex)]
      {:name (-> (:title sc)
                 (str/replace "<case>" (:case row))
                 (str/replace "<ms>" (str (:ms row))))
       :feature-file file
       :feature-name feature-name
       :tags (inherited-tags feature-tags rule-tags (:tags sc) (:tags ex))
       :expected-status :passed
       :expected-fail-step nil
       :pending-step nil
       :duration-floor-ms (:ms row)
       :serial-group nil})
    [(-> sc
         (select-keys [:name :expected-status :expected-fail-step
                       :pending-step :duration-floor-ms :serial-group])
         (assoc :feature-file file
                :feature-name feature-name
                :tags (inherited-tags feature-tags rule-tags (:tags sc) [])))]))

(defn- manifest-entries
  "Per-PICKLE manifest entries for one feature: top-level scenarios first,
   then each Rule's scenarios (matching rendered order)."
  [{:keys [file name tags scenarios rules]}]
  (vec (concat
        (mapcat #(scenario-entries file name tags [] %) scenarios)
        (mapcat (fn [rule]
                  (mapcat #(scenario-entries file name tags (:tags rule) %)
                          (:scenarios rule)))
                rules))))

;; -----------------------------------------------------------------------------
;; Generation (pure) + materialization (IO)
;; -----------------------------------------------------------------------------

(defn- generate
  "Pure: (profile-key, seed) -> {:files [[relpath content] ...] :manifest m}.
   Scratch paths are baked into marker step text as repo-root-relative paths
   (deterministic bytes, no absolute paths in the corpus)."
  [profile-key seed]
  (let [profile (or (get profiles profile-key)
                    (throw (ex-info "Unknown corpus profile"
                                    {:type :corpus/unknown-profile
                                     :profile profile-key
                                     :known (vec (keys profiles))})))
        id (str (name profile-key) "-" seed)
        dir (str "target/corpus/" id)
        scratch-path-for (fn [group] (str dir "/scratch/" group ".log"))
        rng (java.util.Random. (long seed))
        counter (volatile! 0)
        next-n (fn [] (vswap! counter inc))
        features (-> (core-features rng profile next-n)
                     (conj (serial-feature rng profile next-n scratch-path-for))
                     (conj (control-feature rng profile next-n scratch-path-for))
                     (->> (add-filler rng profile next-n)))
        groups (mapv #(str "g" (inc %)) (range (:serial-groups profile)))
        manifest {:generator-version generator-version
                  :seed seed
                  :profile profile-key
                  :config {:allow-pending? (:allow-pending? profile)}
                  :scenarios (vec (mapcat manifest-entries features))
                  :scratch-files (into {} (map (fn [g] [g (scratch-path-for g)])
                                               (conj groups "control")))
                  :broken {:file "broken/broken.feature"
                           :tags ["@broken"]
                           :role (str "sl-i608 planning-time-filter acceptance case: "
                                      "run with @broken tag-excluded must pass planning; "
                                      "run without the filter must exit 2 (undefined step).")}}
        config-text (pr-str {:runner {:allow-pending? (:allow-pending? profile)}})
        files (-> [["shiftlefter.edn" config-text]]
                  (into (map (fn [f] [(str "features/" (:file f)) (render-feature f)])
                             features))
                  (conj ["broken/broken.feature" broken-feature-text])
                  (conj ["manifest.edn" (pr-str manifest)]))]
    {:id id :dir dir :files files :manifest manifest}))

(defn write-corpus!
  "Materialize (profile, seed) under target/corpus/<profile>-<seed>/, wiping
   any previous generation (and its scratch/run outputs) first. Returns
   {:id :dir :features-dir :broken-dir :scratch-dir :manifest :files} where
   :files is the vector of written relpaths (for byte-identity checks)."
  [{:keys [profile seed] :or {profile :default}}]
  (let [{:keys [id dir files manifest]} (generate profile seed)]
    (when-not (s/valid? :corpus/manifest manifest)
      (throw (ex-info "Generated manifest fails its spec"
                      {:type :corpus/invalid-manifest
                       :explain (s/explain-str :corpus/manifest manifest)})))
    (when (fs/exists? dir) (fs/delete-tree dir))
    (fs/create-dirs (str dir "/scratch"))
    (doseq [[relpath content] files]
      (let [path (str dir "/" relpath)]
        (fs/create-dirs (fs/parent path))
        (spit path content)))
    {:id id
     :dir dir
     :features-dir (str dir "/features")
     :broken-dir (str dir "/broken")
     :scratch-dir (str dir "/scratch")
     :manifest manifest
     :files (mapv first files)}))
